### ISSUE TITLE
Trying to understand the two available options more clearly

### ISSUE THREAD

**Issue by kozross** [Snaipe/libcsptr#9]
In the build descriptionf file, you define two custom options - one for a variadic sentinel, the other to always use malloc. This might sound stupid, but what's the idea behind that? I'm basically trying to understand your code, and this is currently eluding me. Could you please help me understand?

**Comment by Snaipe** [comment]
I ought to document these two. Will do so asap.

The option to always use malloc is there to allow certain kinds of inlining optimisations done by the compiler; although the code did change a lot since then, so I should probably do some profiling again to see if it is still relevant.

The other option is there to address a request to spare the 4 (or 8 on 64 bit systems) unused bytes acting as a sentinel in the struct-based variadic parameter.
Because not having a sentinel yields to nonstandard C99, it is off by default, but people working on embedded systems with very limited memory *and* compiling with a C compiler supporting GNU extensions can activate this option.

**Comment by kozross** [comment]
Thanks - that clears it up perfectly!
